#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname --  "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Create important directory
mkdir  $SCRIPT_DIR/.converting
mkdir  $SCRIPT_DIR/.process
mkdir  $SCRIPT_DIR/input

base_cur=$SCRIPT_DIR/input
indir=(
  Alternate Busy Cross Default Dgn1
  Dgn2 Hand Help Horizontal Link
  Move Text Unavailable Vertical Work
)
for fil in "${indir[@]}"; do
  mkdir -p "$base_cur/${fil}"
done

# Create important input directory
mkdir $SCRIPT_DIR/autosort

# Give permission to each script
chmod_bsh=$SCRIPT_DIR
scrp=(
	convert detail sorting start
)
for srp in "${scrp[@]}"; do
	chmod +x "$chmod_bsh/${srp}"
done

# Remove this file once done
# rm $SCRIPT_DIR/create-directory-first
