#! /bin/bash

# Create important directory
mkdir  $HOME/win2xcur-script/.converting
mkdir  $HOME/win2xcur-script/.process
mkdir  $HOME/win2xcur-script/input

base_cur=$HOME/win2xcur-script/input
indir=(
  Alternate Busy Cross Default Dgn1
  Dgn2 Hand Help Horizontal Link
  Move Text Unavailable Vertical Work
)
for fil in "${indir[@]}"; do
  mkdir -p "$base_cur/${fil}"
done

# Create important input directory
mkdir $HOME/win2xcur-script/autosort

# Give permission to each script
chmod_bsh=$HOME/win2xcur-script
scrp=(
	convert detail sorting start
)
for srp in "${scrp[@]}"; do
	chmod +x "$chmod_bsh/${srp}"
done

# Remove this file once done
rm $HOME/win2xcur-script/create-directory-first
